### ISSUE TITLE
Could not find a declaration file for module '@formkit/auto-animate'. in Yarn berry

### ISSUE THREAD

**Issue by Dann1y** [formkit/auto-animate#150]
```
import { getTransitionSizes, AutoAnimationPlugin } from "@formkit/auto-animate";
```
red line -> "@formkit/auto-animate"

// error
```Could not find a declaration file for module '@formkit/auto-animate'.
'{path}/.yarn/cache/@formkit-auto-animate-npm-0.7.0-459537d1b4-c714bf9609.zip/node_modules/@formkit/auto-animate/index.mjs' implicitly has an 'any' type.

  There are types at '{path}/.yarn/cache/@formkit-auto-animate-npm-0.7.0-459537d1b4-c714bf9609.zip/node_modules/@formkit/auto-animate/index.d.ts',
but this result could not be resolved when respecting package.json

"exports". The '@formkit/auto-animate' library may need to update its package.json or typings.ts(7016)
```

{path} is my local directory path.
My environment
- MacOS applie silicon M1 pro
- yarn workspace (monorepo)
- yarn berry (pnp mode)

I'm having a problem with the type, but I'm not sure, so please check this problem.
Please let me know if I'm using it the wrong way

**Comment by bengry** [comment]
I've fixed this in https://github.com/formkit/auto-animate/pull/151.

If you need a temporary solution, you can use `patch-package` and this patch:
```diff
diff --git a/node_modules/@formkit/auto-animate/package.json b/node_modules/@formkit/auto-animate/package.json
index e224bd5..d961409 100644
--- a/node_modules/@formkit/auto-animate/package.json
+++ b/node_modules/@formkit/auto-animate/package.json
@@ -52,6 +52,7 @@
     },
     ".": {
       "import": "./index.mjs",
+      "types": "./index.d.ts",
       "default": "./index.mjs"
     }
   }
```

**Comment by Dann1y** [comment]
@bengry 
Thanks for your fix 🙏🏻
I will check after merge #151 PR!

**Comment by SlavenIvanov** [comment]
I am still experiencing this issue with `"@formkit/auto-animate": "^0.8.2"`. Is there fix for this that doesn't include editing node_modules?
